CREATE DATABASE tpch;

USE tpch;

CREATE TABLE Customer (
    CUSTKEY INT PRIMARY KEY,
    NAME VARCHAR(25),
    ADDRESS VARCHAR(40),
    NATIONKEY INT,
    PHONE CHAR(15),
    ACCTBAL DECIMAL(15, 2),
    MKTSEGMENT CHAR(10),
    COMMENT VARCHAR(117)
);

TRUNCATE TABLE Customer;

SELECT * FROM Customer;

BULK INSERT Customer
FROM '/data/customer.tbl'
WITH (
    FIELDTERMINATOR = '|',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1
);

CREATE TABLE Orders (
    ORDERKEY INT PRIMARY KEY,
    CUSTKEY INT,
    ORDERSTATUS CHAR(1),
    TOTALPRICE DECIMAL(15, 2),
    ORDERDATE DATE,
    ORDERPRIORITY CHAR(15),
    CLERK CHAR(15),
    SHIPPRIORITY INT,
    COMMENT VARCHAR(79),
    CONSTRAINT FK_Orders_Customer FOREIGN KEY (CUSTKEY) REFERENCES Customer(CUSTKEY)
);

BULK INSERT Orders
FROM '/data/orders.tbl'
WITH (
    FIELDTERMINATOR = '|',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1
);

CREATE TABLE LineItem (
    ORDERKEY INT,
    PARTKEY INT,
    SUPPKEY INT,
    LINENUMBER INT,
    QUANTITY DECIMAL(15, 2),
    EXTENDEDPRICE DECIMAL(15, 2),
    DISCOUNT DECIMAL(15, 2),
    TAX DECIMAL(15, 2),
    RETURNFLAG CHAR(1),
    LINESTATUS CHAR(1),
    SHIPDATE DATE,
    COMMITDATE DATE,
    RECEIPTDATE DATE,
    SHIPINSTRUCT CHAR(25),
    SHIPMODE CHAR(10),
    COMMENT VARCHAR(44),
    PRIMARY KEY (ORDERKEY, LINENUMBER),
    CONSTRAINT FK_LineItem_Order FOREIGN KEY (ORDERKEY) REFERENCES Orders(ORDERKEY)
);

BULK INSERT LineItem
FROM '/data/lineitem.tbl'
WITH (
    FIELDTERMINATOR = '|',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1
);

SET STATISTICS TIME ON;
SET STATISTICS IO ON;

select * from LineItem;
-- 1. WHERE
-- predicate pushdown
SELECT 
    O.ORDERKEY,
    SUM(LI.QUANTITY) AS ORDER_QUANTITY,
    COUNT(LI.LINENUMBER) AS TOTAL_LINE
FROM Orders O
INNER JOIN LineItem LI ON O.ORDERKEY = LI.ORDERKEY
WHERE O.ORDERPRIORITY = '5-LOW' AND LI.DISCOUNT > 0
GROUP BY O.ORDERKEY
ORDER BY O.ORDERKEY; -- 296,299 rows

WITH FilteredOrders AS (
    SELECT * 
    FROM Orders 
    WHERE ORDERPRIORITY = '5-LOW'
)
SELECT 
    O.ORDERKEY,
    SUM(LI.QUANTITY) AS ORDER_QUANTITY,
    COUNT(LI.LINENUMBER) AS TOTAL_LINE
FROM FilteredOrders O
INNER JOIN LineItem LI ON O.ORDERKEY = LI.ORDERKEY
WHERE LI.DISCOUNT > 0
GROUP BY O.ORDERKEY
ORDER BY O.ORDERKEY; -- 296,299 rows

WITH FilteredOrders AS (
    -- Filter orders with '5-LOW' priority
    SELECT * 
    FROM Orders 
    WHERE ORDERPRIORITY = '5-LOW'
),
FilteredLineItems AS (
    -- Filter line items with a discount greater than 0
    SELECT * 
    FROM LineItem 
    WHERE DISCOUNT > 0
)
SELECT 
    O.ORDERKEY,
    SUM(LI.QUANTITY) AS ORDER_QUANTITY,
    COUNT(LI.LINENUMBER) AS TOTAL_LINE
FROM FilteredOrders O
INNER JOIN FilteredLineItems LI ON O.ORDERKEY = LI.ORDERKEY
GROUP BY O.ORDERKEY
ORDER BY O.ORDERKEY; -- 296,299 rows



select * from Orders;
-- FETCH CUSTKEY, NAME & TOTALSPENT OF EACH CUSTOMER WITH ORDERPRIORITY LIKE '%-LOW'
SELECT C.CUSTKEY, C.NAME, TotalSpent
FROM Customer C
INNER JOIN (
    SELECT 
        CUSTKEY, 
        SUM(TOTALPRICE) AS TotalSpent,
        ORDERPRIORITY
    FROM Orders
    GROUP BY CUSTKEY, ORDERPRIORITY
) O ON C.CUSTKEY = O.CUSTKEY
WHERE O.ORDERPRIORITY LIKE '%-LOW'
ORDER BY C.CUSTKEY;

SELECT C.CUSTKEY, C.NAME, TotalSpent
FROM Customer C
INNER JOIN (
    SELECT 
        CUSTKEY, 
        SUM(TOTALPRICE) AS TotalSpent,
        ORDERPRIORITY
    FROM Orders
    WHERE ORDERPRIORITY LIKE '%-LOW'
    GROUP BY CUSTKEY, ORDERPRIORITY
) O ON C.CUSTKEY = O.CUSTKEY
ORDER BY C.CUSTKEY;

WITH a AS (
    SELECT 
        CUSTKEY, 
        SUM(TOTALPRICE) AS TotalSpent,
        ORDERPRIORITY
    FROM Orders
    WHERE ORDERPRIORITY LIKE '%-LOW'
    GROUP BY CUSTKEY, ORDERPRIORITY
)
SELECT C.CUSTKEY, C.NAME, TotalSpent
FROM Customer C
INNER JOIN a ON C.CUSTKEY = a.CUSTKEY
ORDER BY C.CUSTKEY;

-- CALCULATE TOTAL QUANTITY OF PARTS OF EACH ORDER
-- group by
SELECT
    ORDERKEY,
    SUM(QUANTITY) AS TOTAL_QTY
FROM LineItem
GROUP BY ORDERKEY
ORDER BY ORDERKEY; -- 1,500,000 ROWS


-- using subquery
SELECT DISTINCT 
       LI.ORDERKEY, 
       (SELECT SUM(LI2.QUANTITY) 
        FROM LineItem LI2 
        WHERE LI2.ORDERKEY = LI.ORDERKEY) AS TOTAL_QTY
FROM LineItem LI
ORDER BY LI.ORDERKEY; -- 1,500,000 ROWS

-- using window function
SELECT DISTINCT 
    ORDERKEY,
    SUM(QUANTITY) OVER (PARTITION BY ORDERKEY) AS TOTAL_QTY
FROM LineItem
ORDER BY ORDERKEY; -- 1,500,000 rows

-- CALCULATE TOTAL QUANTITY OF PARTS A CUSTOMER ORDERED
-- having
SELECT C.CUSTKEY, 
       SUM(LI.QUANTITY) AS TOTAL_QTY
FROM Customer C
INNER JOIN Orders O ON C.CUSTKEY = O.CUSTKEY
INNER JOIN LineItem LI ON O.ORDERKEY = LI.ORDERKEY
GROUP BY C.CUSTKEY
HAVING SUM(LI.QUANTITY) > 100
ORDER BY C.CUSTKEY; -- 99,974 ROWS

-- CTE
WITH AggregatedData AS (
    SELECT DISTINCT C.CUSTKEY, 
           SUM(LI.QUANTITY) OVER (PARTITION BY C.CUSTKEY) AS TOTAL_QTY
    FROM Customer C
    INNER JOIN Orders O ON C.CUSTKEY = O.CUSTKEY
    INNER JOIN LineItem LI ON O.ORDERKEY = LI.ORDERKEY
)
SELECT CUSTKEY, TOTAL_QTY
FROM AggregatedData
WHERE TOTAL_QTY > 100
ORDER BY CUSTKEY; -- 99,974 ROWS

SELECT CUSTKEY, TOTAL_QTY
FROM (
    SELECT C.CUSTKEY, 
           SUM(LI.QUANTITY) AS TOTAL_QTY
    FROM Customer C
    INNER JOIN Orders O ON C.CUSTKEY = O.CUSTKEY
    INNER JOIN LineItem LI ON O.ORDERKEY = LI.ORDERKEY
    GROUP BY C.CUSTKEY
) AS Aggregated
WHERE TOTAL_QTY > 100; -- 99,974 ROWS















