version: '3.8'
services:
  superset:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      ./.env
    ports:
      - "8088:8088"
    depends_on:
      - superset-postgres
    networks:
      - superset-network
    volumes:
      - superset-data:/app/superset_home

  superset-postgres:
    image: postgres:15
    container_name: superset-postgres
    env_file:
      ./.env
    ports:
      - "5432:5432"
    networks:
      - superset-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  superset-network:
    driver: bridge

volumes:
  superset-data:
  postgres-data: